# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'robotHelpFrame.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_helpFrame(object):
    def setupUi(self, helpFrame):
        helpFrame.setObjectName("helpFrame")
        helpFrame.resize(640, 620)
        self.gridLayout = QtWidgets.QGridLayout(helpFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.emailFrame = QtWidgets.QFrame(helpFrame)
        self.emailFrame.setStyleSheet("background: transparent;")
        self.emailFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.emailFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.emailFrame.setObjectName("emailFrame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.emailFrame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.helpdeskFrame = QtWidgets.QFrame(self.emailFrame)
        self.helpdeskFrame.setStyleSheet("background: transparent;")
        self.helpdeskFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.helpdeskFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.helpdeskFrame.setObjectName("helpdeskFrame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.helpdeskFrame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.helpdeskLabel = QtWidgets.QLabel(self.helpdeskFrame)
        self.helpdeskLabel.setObjectName("helpdeskLabel")
        self.verticalLayout_4.addWidget(self.helpdeskLabel)
        self.helpdeskButton = QtWidgets.QPushButton(self.helpdeskFrame)
        self.helpdeskButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.helpdeskButton.setStyleSheet("QPushButton {\n"
"  background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.119403 rgba(255, 0, 38, 255), stop:1 rgba(255, 255, 255, 255));\n"
"  border-color: rgb(203, 45, 69);\n"
"  border-width: 3px;        \n"
"  border-style: solid;\n"
"  border-radius: 40px;\n"
"  margin:30px;\n"
"  padding:30px;\n"
"}")
        self.helpdeskButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/helpdesk.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.helpdeskButton.setIcon(icon)
        self.helpdeskButton.setIconSize(QtCore.QSize(100, 100))
        self.helpdeskButton.setObjectName("helpdeskButton")
        self.verticalLayout_4.addWidget(self.helpdeskButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.verticalLayout_5.addWidget(self.helpdeskFrame)
        self.emailButton = QtWidgets.QPushButton(self.emailFrame)
        self.emailButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.emailButton.setStyleSheet("QPushButton {\n"
"  background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.119403 rgba(255, 255, 255, 255), stop:1 rgba(255, 0, 38, 255));\n"
"  border-color: rgb(203, 45, 69);\n"
"  border-width: 3px;        \n"
"  border-style: solid;\n"
"  border-radius: 40px;\n"
"  margin:30px;\n"
"  padding:30px;\n"
"}")
        self.emailButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/email.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.emailButton.setIcon(icon1)
        self.emailButton.setIconSize(QtCore.QSize(100, 100))
        self.emailButton.setObjectName("emailButton")
        self.verticalLayout_5.addWidget(self.emailButton)
        self.emailLabel_2 = QtWidgets.QLabel(self.emailFrame)
        self.emailLabel_2.setObjectName("emailLabel_2")
        self.verticalLayout_5.addWidget(self.emailLabel_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.gridLayout.addWidget(self.emailFrame, 0, 0, 1, 1)
        self.helpdeskLabel.setBuddy(self.helpdeskButton)
        self.emailLabel_2.setBuddy(self.emailButton)

        self.retranslateUi(helpFrame)
        QtCore.QMetaObject.connectSlotsByName(helpFrame)

    def retranslateUi(self, helpFrame):
        _translate = QtCore.QCoreApplication.translate
        helpFrame.setWindowTitle(_translate("helpFrame", "Frame"))
        self.helpdeskLabel.setText(_translate("helpFrame", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#cb2d45;\">HelpDesk</span></p></body></html>"))
        self.emailLabel_2.setText(_translate("helpFrame", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#cb2d45;\">E-mail a Teacher</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    helpFrame = QtWidgets.QFrame()
    ui = Ui_helpFrame()
    ui.setupUi(helpFrame)
    helpFrame.show()
    sys.exit(app.exec_())
