# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'robotHelpdeskOldTicketsFrame.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_oldTicketsFrame(object):
    def setupUi(self, oldTicketsFrame):
        oldTicketsFrame.setObjectName("oldTicketsFrame")
        oldTicketsFrame.resize(640, 480)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(oldTicketsFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.helpdeskFrame = QtWidgets.QFrame(oldTicketsFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.helpdeskFrame.sizePolicy().hasHeightForWidth())
        self.helpdeskFrame.setSizePolicy(sizePolicy)
        self.helpdeskFrame.setStyleSheet("background: transparent;")
        self.helpdeskFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.helpdeskFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.helpdeskFrame.setObjectName("helpdeskFrame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.helpdeskFrame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.helpdeskLabel = QtWidgets.QLabel(self.helpdeskFrame)
        self.helpdeskLabel.setObjectName("helpdeskLabel")
        self.verticalLayout_4.addWidget(self.helpdeskLabel)
        self.verticalLayout_2.addWidget(self.helpdeskFrame)
        self.ticketsFrame = QtWidgets.QFrame(oldTicketsFrame)
        self.ticketsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ticketsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ticketsFrame.setObjectName("ticketsFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.ticketsFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.reloadFrame = QtWidgets.QFrame(self.ticketsFrame)
        self.reloadFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.reloadFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.reloadFrame.setObjectName("reloadFrame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.reloadFrame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.reloadButton = QtWidgets.QPushButton(self.reloadFrame)
        self.reloadButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.reloadButton.setStyleSheet("color: rgb(179, 0, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.reloadButton.setObjectName("reloadButton")
        self.gridLayout_2.addWidget(self.reloadButton, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.reloadFrame)
        self.tableFrame = QtWidgets.QFrame(self.ticketsFrame)
        self.tableFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tableFrame.setObjectName("tableFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.tableFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.tabTicketsWidget = QtWidgets.QTabWidget(self.tableFrame)
        self.tabTicketsWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabTicketsWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabTicketsWidget.setObjectName("tabTicketsWidget")
        self.tabOpenTickets = QtWidgets.QWidget()
        self.tabOpenTickets.setObjectName("tabOpenTickets")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tabOpenTickets)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.viewOpenTickets = QtWidgets.QTableView(self.tabOpenTickets)
        self.viewOpenTickets.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.viewOpenTickets.setObjectName("viewOpenTickets")
        self.gridLayout_5.addWidget(self.viewOpenTickets, 0, 0, 1, 1)
        self.tabTicketsWidget.addTab(self.tabOpenTickets, "")
        self.tabClosedTickets = QtWidgets.QWidget()
        self.tabClosedTickets.setObjectName("tabClosedTickets")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tabClosedTickets)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.viewClosedTickets = QtWidgets.QTableView(self.tabClosedTickets)
        self.viewClosedTickets.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.viewClosedTickets.setObjectName("viewClosedTickets")
        self.gridLayout_7.addWidget(self.viewClosedTickets, 0, 0, 1, 1)
        self.tabTicketsWidget.addTab(self.tabClosedTickets, "")
        self.gridLayout.addWidget(self.tabTicketsWidget, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.tableFrame)
        self.verticalLayout_2.addWidget(self.ticketsFrame)

        self.retranslateUi(oldTicketsFrame)
        self.tabTicketsWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(oldTicketsFrame)

    def retranslateUi(self, oldTicketsFrame):
        _translate = QtCore.QCoreApplication.translate
        oldTicketsFrame.setWindowTitle(_translate("oldTicketsFrame", "Frame"))
        self.helpdeskLabel.setText(_translate("oldTicketsFrame", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#cb2d45;\">HelpDesk</span></p></body></html>"))
        self.reloadButton.setText(_translate("oldTicketsFrame", "Reload list of tickets"))
        self.tabTicketsWidget.setTabText(self.tabTicketsWidget.indexOf(self.tabOpenTickets), _translate("oldTicketsFrame", "Open Tickets"))
        self.tabTicketsWidget.setTabText(self.tabTicketsWidget.indexOf(self.tabClosedTickets), _translate("oldTicketsFrame", "Closed Tickets"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    oldTicketsFrame = QtWidgets.QFrame()
    ui = Ui_oldTicketsFrame()
    ui.setupUi(oldTicketsFrame)
    oldTicketsFrame.show()
    sys.exit(app.exec_())
