# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'robotHelpdeskTicketsFrame.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_helpDeskFrame(object):
    def setupUi(self, helpDeskFrame):
        helpDeskFrame.setObjectName("helpDeskFrame")
        helpDeskFrame.resize(640, 480)
        self.verticalLayout = QtWidgets.QVBoxLayout(helpDeskFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.helpdeskLabel = QtWidgets.QLabel(helpDeskFrame)
        self.helpdeskLabel.setObjectName("helpdeskLabel")
        self.verticalLayout.addWidget(self.helpdeskLabel)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.logoHelpLabel = QtWidgets.QLabel(helpDeskFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logoHelpLabel.sizePolicy().hasHeightForWidth())
        self.logoHelpLabel.setSizePolicy(sizePolicy)
        self.logoHelpLabel.setStyleSheet("")
        self.logoHelpLabel.setObjectName("logoHelpLabel")
        self.verticalLayout.addWidget(self.logoHelpLabel)
        self.subjectLabel = QtWidgets.QLabel(helpDeskFrame)
        self.subjectLabel.setStyleSheet("color: rgb(168, 11, 21);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.subjectLabel.setObjectName("subjectLabel")
        self.verticalLayout.addWidget(self.subjectLabel)
        self.subjectInput = QtWidgets.QLineEdit(helpDeskFrame)
        self.subjectInput.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border: 2px solid red; \n"
"")
        self.subjectInput.setObjectName("subjectInput")
        self.verticalLayout.addWidget(self.subjectInput)
        self.newTicketLabel = QtWidgets.QLabel(helpDeskFrame)
        self.newTicketLabel.setStyleSheet("color: rgb(168, 11, 21);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.newTicketLabel.setObjectName("newTicketLabel")
        self.verticalLayout.addWidget(self.newTicketLabel)
        self.newTicketTextBox = QtWidgets.QTextEdit(helpDeskFrame)
        self.newTicketTextBox.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border: 2px solid red; \n"
"")
        self.newTicketTextBox.setObjectName("newTicketTextBox")
        self.verticalLayout.addWidget(self.newTicketTextBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.attachButton = QtWidgets.QPushButton(helpDeskFrame)
        self.attachButton.setStyleSheet("background-color: rgb(168, 11, 21);\n"
"color: white;")
        self.attachButton.setObjectName("attachButton")
        self.horizontalLayout.addWidget(self.attachButton)
        self.finishButton = QtWidgets.QPushButton(helpDeskFrame)
        self.finishButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.finishButton.setStyleSheet("background-color: rgb(168, 11, 21);\n"
"color: white;")
        self.finishButton.setObjectName("finishButton")
        self.horizontalLayout.addWidget(self.finishButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.oldTicketsButton = QtWidgets.QCommandLinkButton(helpDeskFrame)
        self.oldTicketsButton.setStyleSheet("color: rgb(168, 11, 21);\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.oldTicketsButton.setObjectName("oldTicketsButton")
        self.verticalLayout.addWidget(self.oldTicketsButton)

        self.retranslateUi(helpDeskFrame)
        QtCore.QMetaObject.connectSlotsByName(helpDeskFrame)

    def retranslateUi(self, helpDeskFrame):
        _translate = QtCore.QCoreApplication.translate
        helpDeskFrame.setWindowTitle(_translate("helpDeskFrame", "Frame"))
        self.helpdeskLabel.setText(_translate("helpDeskFrame", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#cb2d45;\">HelpDesk</span></p></body></html>"))
        self.logoHelpLabel.setText(_translate("helpDeskFrame", "<html><head/><body><p align=\"center\"><img src=\":/icons/helpdesk_13.png\"/></p></body></html>"))
        self.subjectLabel.setText(_translate("helpDeskFrame", "Introduce a name for your ticket:"))
        self.newTicketLabel.setText(_translate("helpDeskFrame", "Write down below the text of your new ticket:"))
        self.attachButton.setText(_translate("helpDeskFrame", "Attachments"))
        self.finishButton.setText(_translate("helpDeskFrame", "Finish ticket"))
        self.oldTicketsButton.setText(_translate("helpDeskFrame", "Or go to see the status of your older tickets"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    helpDeskFrame = QtWidgets.QFrame()
    ui = Ui_helpDeskFrame()
    ui.setupUi(helpDeskFrame)
    helpDeskFrame.show()
    sys.exit(app.exec_())
