# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'robotPaperworkFrame.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_paperworkFrame(object):
    def setupUi(self, paperworkFrame):
        paperworkFrame.setObjectName("paperworkFrame")
        paperworkFrame.resize(659, 601)
        self.horizontalLayout = QtWidgets.QHBoxLayout(paperworkFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.requestDocFrame = QtWidgets.QFrame(paperworkFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.requestDocFrame.sizePolicy().hasHeightForWidth())
        self.requestDocFrame.setSizePolicy(sizePolicy)
        self.requestDocFrame.setStyleSheet("background: transparent;")
        self.requestDocFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.requestDocFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.requestDocFrame.setObjectName("requestDocFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.requestDocFrame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.requestDocLabel = QtWidgets.QLabel(self.requestDocFrame)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        self.requestDocLabel.setFont(font)
        self.requestDocLabel.setObjectName("requestDocLabel")
        self.verticalLayout_3.addWidget(self.requestDocLabel)
        self.requestDocButton = QtWidgets.QPushButton(self.requestDocFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.requestDocButton.sizePolicy().hasHeightForWidth())
        self.requestDocButton.setSizePolicy(sizePolicy)
        self.requestDocButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.requestDocButton.setStyleSheet("QPushButton {\n"
"  border-color: rgb(51, 130, 173);\n"
"  background: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(51, 130, 173, 255), stop:1 rgba(255, 255, 255, 255));\n"
"  border-width: 3px;        \n"
"  border-style: solid;\n"
"  border-radius: 40px;\n"
"  margin:30px;\n"
"  padding:30px;\n"
"}")
        self.requestDocButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/import-removebg-preview.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.requestDocButton.setIcon(icon)
        self.requestDocButton.setIconSize(QtCore.QSize(150, 150))
        self.requestDocButton.setObjectName("requestDocButton")
        self.verticalLayout_3.addWidget(self.requestDocButton)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.toRequestList = QtWidgets.QListWidget(self.requestDocFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toRequestList.sizePolicy().hasHeightForWidth())
        self.toRequestList.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.toRequestList.setFont(font)
        self.toRequestList.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toRequestList.setStyleSheet("QListWidget {\n"
"  \n"
"}\n"
"QListWidget::item {\n"
"    border: 1px solid rgba(51, 130, 173,180); \n"
"    border-radius: 10px;\n"
"    background: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 200), stop:1 rgba(51, 130, 173, 200));\n"
"}")
        self.toRequestList.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.toRequestList.setMovement(QtWidgets.QListView.Static)
        self.toRequestList.setFlow(QtWidgets.QListView.TopToBottom)
        self.toRequestList.setProperty("isWrapping", False)
        self.toRequestList.setResizeMode(QtWidgets.QListView.Adjust)
        self.toRequestList.setUniformItemSizes(True)
        self.toRequestList.setBatchSize(100)
        self.toRequestList.setWordWrap(False)
        self.toRequestList.setSelectionRectVisible(False)
        self.toRequestList.setObjectName("toRequestList")
        item = QtWidgets.QListWidgetItem()
        self.toRequestList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.toRequestList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.toRequestList.addItem(item)
        self.verticalLayout_3.addWidget(self.toRequestList)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.horizontalLayout.addWidget(self.requestDocFrame)
        self.sendDocFrame = QtWidgets.QFrame(paperworkFrame)
        self.sendDocFrame.setStyleSheet("background: transparent;")
        self.sendDocFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sendDocFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sendDocFrame.setObjectName("sendDocFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.sendDocFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.sendDocLabel = QtWidgets.QLabel(self.sendDocFrame)
        self.sendDocLabel.setObjectName("sendDocLabel")
        self.verticalLayout.addWidget(self.sendDocLabel)
        self.sendDocButton = QtWidgets.QPushButton(self.sendDocFrame)
        self.sendDocButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sendDocButton.setAutoFillBackground(False)
        self.sendDocButton.setStyleSheet("QPushButton {\n"
"  border-color: rgb(51, 130, 173);\n"
"  background: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(51, 130, 173, 255), stop:1 rgba(255, 255, 255, 255));\n"
"  border-width: 3px;        \n"
"  border-style: solid;\n"
"  border-radius: 40px;\n"
"  margin:30px;\n"
"  padding:30px;\n"
"}")
        self.sendDocButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/export-removebg-preview.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sendDocButton.setIcon(icon1)
        self.sendDocButton.setIconSize(QtCore.QSize(150, 150))
        self.sendDocButton.setObjectName("sendDocButton")
        self.verticalLayout.addWidget(self.sendDocButton)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.toSentList = QtWidgets.QListWidget(self.sendDocFrame)
        self.toSentList.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toSentList.setStyleSheet("QListWidget {\n"
"  \n"
"}\n"
"QListWidget::item {\n"
"    border: 1px solid rgba(51, 130, 173,180); \n"
"    border-radius: 10px;\n"
"    background: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 200), stop:1 rgba(51, 130, 173, 200));\n"
"}")
        self.toSentList.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.toSentList.setProperty("isWrapping", False)
        self.toSentList.setWordWrap(False)
        self.toSentList.setObjectName("toSentList")
        item = QtWidgets.QListWidgetItem()
        self.toSentList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.toSentList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.toSentList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.toSentList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.toSentList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.toSentList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.toSentList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.toSentList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.toSentList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.toSentList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.toSentList.addItem(item)
        self.verticalLayout.addWidget(self.toSentList)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.horizontalLayout.addWidget(self.sendDocFrame)
        self.requestDocLabel.setBuddy(self.requestDocButton)
        self.sendDocLabel.setBuddy(self.sendDocButton)

        self.retranslateUi(paperworkFrame)
        QtCore.QMetaObject.connectSlotsByName(paperworkFrame)

    def retranslateUi(self, paperworkFrame):
        _translate = QtCore.QCoreApplication.translate
        paperworkFrame.setWindowTitle(_translate("paperworkFrame", "Frame"))
        self.requestDocLabel.setText(_translate("paperworkFrame", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#3382ad;\">Request Document</span></p></body></html>"))
        __sortingEnabled = self.toRequestList.isSortingEnabled()
        self.toRequestList.setSortingEnabled(False)
        item = self.toRequestList.item(0)
        item.setText(_translate("paperworkFrame", "Adeverință de Student"))
        item = self.toRequestList.item(1)
        item.setText(_translate("paperworkFrame", "Adeverință de Licență"))
        item = self.toRequestList.item(2)
        item.setText(_translate("paperworkFrame", "Situație Școlară"))
        self.toRequestList.setSortingEnabled(__sortingEnabled)
        self.sendDocLabel.setText(_translate("paperworkFrame", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#3382ad;\">Send Document</span></p></body></html>"))
        __sortingEnabled = self.toSentList.isSortingEnabled()
        self.toSentList.setSortingEnabled(False)
        item = self.toSentList.item(0)
        item.setText(_translate("paperworkFrame", "Fișă de Lichidare"))
        item = self.toSentList.item(1)
        item.setText(_translate("paperworkFrame", "Fișă Acceptare Bursă"))
        item = self.toSentList.item(2)
        item.setText(_translate("paperworkFrame", "Adeverință Cercetare Elaborare Licență"))
        item = self.toSentList.item(3)
        item.setText(_translate("paperworkFrame", "Declarație Autenticitate Lucrare Licență"))
        item = self.toSentList.item(4)
        item.setText(_translate("paperworkFrame", "Cerere Aprobare Licență"))
        item = self.toSentList.item(5)
        item.setText(_translate("paperworkFrame", "Cerere Cazare Cămin"))
        item = self.toSentList.item(6)
        item.setText(_translate("paperworkFrame", "Cerere de Echivalare"))
        item = self.toSentList.item(7)
        item.setText(_translate("paperworkFrame", "Cerere de Transfer"))
        item = self.toSentList.item(8)
        item.setText(_translate("paperworkFrame", "Acte Practică"))
        item = self.toSentList.item(9)
        item.setText(_translate("paperworkFrame", "Dovada Plății Taxei"))
        item = self.toSentList.item(10)
        item.setText(_translate("paperworkFrame", "Alegerea Opționalelor"))
        self.toSentList.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    paperworkFrame = QtWidgets.QFrame()
    ui = Ui_paperworkFrame()
    ui.setupUi(paperworkFrame)
    paperworkFrame.show()
    sys.exit(app.exec_())
