# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'robotAskToknePasswordDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AksPassworDialog(object):
    def setupUi(self, AksPasswordDialog):
        AksPasswordDialog.setObjectName("AksPasswordDialog")
        AksPasswordDialog.setWindowModality(QtCore.Qt.NonModal)
        AksPasswordDialog.resize(400, 300)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/bot-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AksPasswordDialog.setWindowIcon(icon)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(AksPasswordDialog)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.titleLabel = QtWidgets.QLabel(AksPasswordDialog)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout_4.addWidget(self.titleLabel)
        self.credentialsLayout = QtWidgets.QVBoxLayout()
        self.credentialsLayout.setObjectName("credentialsLayout")
        self.passwordLayout = QtWidgets.QVBoxLayout()
        self.passwordLayout.setObjectName("passwordLayout")
        self.passwordLabel = QtWidgets.QLabel(AksPasswordDialog)
        self.passwordLabel.setObjectName("passwordLabel")
        self.passwordLayout.addWidget(self.passwordLabel)
        self.passwordEdit = QtWidgets.QLineEdit(AksPasswordDialog)
        self.passwordEdit.setInputMethodHints(QtCore.Qt.ImhHiddenText | QtCore.Qt.ImhSensitiveData)
        self.passwordEdit.setObjectName("passwordEdit")
        self.passwordLayout.addWidget(self.passwordEdit)
        self.retryLayout = QtWidgets.QVBoxLayout()
        self.retryLayout.setObjectName("retryLayout")
        self.tryAgainLabel = QtWidgets.QLabel(AksPasswordDialog)
        self.tryAgainLabel.setObjectName("tryAgainLabel")
        self.retryLayout.addWidget(self.tryAgainLabel)
        self.passwordLayout.addLayout(self.retryLayout)
        self.credentialsLayout.addLayout(self.passwordLayout)
        self.verticalLayout_4.addLayout(self.credentialsLayout)
        self.buttonsLayout = QtWidgets.QHBoxLayout()
        self.buttonsLayout.setObjectName("buttonsLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonsLayout.addItem(spacerItem)
        self.submitButton = QtWidgets.QPushButton(AksPasswordDialog)
        self.submitButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.submitButton.setObjectName("submitButton")
        self.buttonsLayout.addWidget(self.submitButton)
        self.forgotButton = QtWidgets.QPushButton(AksPasswordDialog)
        self.forgotButton.setObjectName("forgotButton")
        self.buttonsLayout.addWidget(self.forgotButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonsLayout.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.buttonsLayout)

        self.retranslateUi(AksPasswordDialog)
        QtCore.QMetaObject.connectSlotsByName(AksPasswordDialog)

    def retranslateUi(self, AksPassworDialog):
        _translate = QtCore.QCoreApplication.translate
        AksPassworDialog.setWindowTitle(_translate("AksPasswordDialog", "Token Password!"))
        self.titleLabel.setText(_translate("AksPasswordDialog",
                                           "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600; color:#2daa0a;\">Input the password used to store the </span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600; color:#2daa0a;\">moodle security token:</span></p></body></html>"))
        self.passwordLabel.setText(_translate("AksPasswordDialog",
                                              "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600; color:#ff3007;\">Password:</span></p></body></html>"))
        self.tryAgainLabel.setText(_translate("AksPasswordDialog",
                                              "<html><head/><body><p align=\"center\"><span style=\" font-size:9pt; color:#f30000;\">Wrong password! Try again!</span></p></body></html>"))
        self.submitButton.setText(_translate("AksPasswordDialog", "Submit"))
        self.forgotButton.setText(_translate("AksPasswordDialog", "Forgot my password"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    AksPassworDialog = QtWidgets.QDialog()
    ui = Ui_AksPassworDialog()
    ui.setupUi(AksPassworDialog)
    AksPassworDialog.show()
    sys.exit(app.exec_())
