# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'robotCoursesFrame.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_coursesFrame(object):
    def setupUi(self, coursesFrame):
        coursesFrame.setObjectName("coursesFrame")
        coursesFrame.resize(640, 480)
        self.horizontalLayout = QtWidgets.QHBoxLayout(coursesFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gradesFrame = QtWidgets.QFrame(coursesFrame)
        self.gradesFrame.setStyleSheet("background: transparent;")
        self.gradesFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.gradesFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.gradesFrame.setObjectName("gradesFrame")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.gradesFrame)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.gradesButton = QtWidgets.QPushButton(self.gradesFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gradesButton.sizePolicy().hasHeightForWidth())
        self.gradesButton.setSizePolicy(sizePolicy)
        self.gradesButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.gradesButton.setStyleSheet("QPushButton {\n"
"  background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.189055 rgba(144, 189, 0, 255), stop:0.900498 rgba(255, 255, 255, 255));\n"
"  border-color: rgb(144, 177, 36);\n"
"  border-width: 3px;        \n"
"  border-style: solid;\n"
"  border-radius: 40px;\n"
"  margin:30px;\n"
"  padding:30px;\n"
"}")
        self.gradesButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/gradesicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gradesButton.setIcon(icon)
        self.gradesButton.setIconSize(QtCore.QSize(100, 100))
        self.gradesButton.setObjectName("gradesButton")
        self.verticalLayout_9.addWidget(self.gradesButton)
        self.gradesLabel = QtWidgets.QLabel(self.gradesFrame)
        self.gradesLabel.setObjectName("gradesLabel")
        self.verticalLayout_9.addWidget(self.gradesLabel)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.gradesFrame)
        self.materialsFrame = QtWidgets.QFrame(coursesFrame)
        self.materialsFrame.setStyleSheet("background: transparent;")
        self.materialsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.materialsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.materialsFrame.setObjectName("materialsFrame")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.materialsFrame)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem1)
        self.materialsLabel = QtWidgets.QLabel(self.materialsFrame)
        self.materialsLabel.setObjectName("materialsLabel")
        self.verticalLayout_8.addWidget(self.materialsLabel)
        self.materialsButton = QtWidgets.QPushButton(self.materialsFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.materialsButton.sizePolicy().hasHeightForWidth())
        self.materialsButton.setSizePolicy(sizePolicy)
        self.materialsButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.materialsButton.setStyleSheet("QPushButton {\n"
"  background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.189055 rgba(144, 189, 0, 255), stop:0.900498 rgba(255, 255, 255, 255));\n"
"  border-color: rgb(144, 177, 36);\n"
"  border-width: 3px;        \n"
"  border-style: solid;\n"
"  border-radius: 40px;\n"
"  margin:30px;\n"
"  padding:30px;\n"
"}")
        self.materialsButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/materialsicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.materialsButton.setIcon(icon1)
        self.materialsButton.setIconSize(QtCore.QSize(100, 100))
        self.materialsButton.setObjectName("materialsButton")
        self.verticalLayout_8.addWidget(self.materialsButton)
        self.horizontalLayout.addWidget(self.materialsFrame)
        self.gradesLabel.setBuddy(self.gradesButton)
        self.materialsLabel.setBuddy(self.materialsButton)

        self.retranslateUi(coursesFrame)
        QtCore.QMetaObject.connectSlotsByName(coursesFrame)
        coursesFrame.setTabOrder(self.gradesButton, self.materialsButton)

    def retranslateUi(self, coursesFrame):
        _translate = QtCore.QCoreApplication.translate
        coursesFrame.setWindowTitle(_translate("coursesFrame", "Frame"))
        self.gradesLabel.setText(_translate("coursesFrame", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#90b124;\">Grades</span></p></body></html>"))
        self.materialsLabel.setText(_translate("coursesFrame", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#90b124;\">Materials</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    coursesFrame = QtWidgets.QFrame()
    ui = Ui_coursesFrame()
    ui.setupUi(coursesFrame)
    coursesFrame.show()
    sys.exit(app.exec_())
