# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'robotAttachmentsDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AttachDialog(object):
    def setupUi(self, AttachDialog):
        AttachDialog.setObjectName("AttachDialog")
        AttachDialog.resize(400, 300)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/export.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AttachDialog.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(AttachDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addButton = QtWidgets.QPushButton(AttachDialog)
        self.addButton.setStyleSheet("background-color: rgb(255, 64, 77);")
        self.addButton.setObjectName("addButton")
        self.horizontalLayout.addWidget(self.addButton)
        self.deleteButton = QtWidgets.QPushButton(AttachDialog)
        self.deleteButton.setStyleSheet("background-color: rgb(255, 64, 77);")
        self.deleteButton.setObjectName("deleteButton")
        self.horizontalLayout.addWidget(self.deleteButton)
        self.okButton = QtWidgets.QPushButton(AttachDialog)
        self.okButton.setStyleSheet("background-color: rgb(255, 64, 77);")
        self.okButton.setObjectName("okButton")
        self.horizontalLayout.addWidget(self.okButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.filesListView = QtWidgets.QListView(AttachDialog)
        self.filesListView.setObjectName("filesListView")
        self.verticalLayout.addWidget(self.filesListView)

        self.retranslateUi(AttachDialog)
        QtCore.QMetaObject.connectSlotsByName(AttachDialog)

    def retranslateUi(self, AttachDialog):
        _translate = QtCore.QCoreApplication.translate
        AttachDialog.setWindowTitle(_translate("AttachDialog", "Attachments"))
        self.addButton.setText(_translate("AttachDialog", "Add"))
        self.deleteButton.setText(_translate("AttachDialog", "Delete"))
        self.okButton.setText(_translate("AttachDialog", "Ok"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    AttachDialog = QtWidgets.QDialog()
    ui = Ui_AttachDialog()
    ui.setupUi(AttachDialog)
    AttachDialog.show()
    sys.exit(app.exec_())
