# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'robotMaterialsFrame.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_materialsFrame(object):
    def setupUi(self, materialsFrame):
        materialsFrame.setObjectName("materialsFrame")
        materialsFrame.resize(803, 630)
        self.verticalLayout = QtWidgets.QVBoxLayout(materialsFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.materialsLabel = QtWidgets.QLabel(materialsFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.materialsLabel.sizePolicy().hasHeightForWidth())
        self.materialsLabel.setSizePolicy(sizePolicy)
        self.materialsLabel.setObjectName("materialsLabel")
        self.verticalLayout.addWidget(self.materialsLabel)
        self.searchMaterialsBox = QtWidgets.QGridLayout()
        self.searchMaterialsBox.setObjectName("searchMaterialsBox")
        self.commandsBar = QtWidgets.QHBoxLayout()
        self.commandsBar.setObjectName("commandsBar")
        self.refreshButton = QtWidgets.QPushButton(materialsFrame)
        self.refreshButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.refreshButton.setStyleSheet("background-color: rgb(154, 217, 59);")
        self.refreshButton.setObjectName("refreshButton")
        self.commandsBar.addWidget(self.refreshButton)
        self.browseLabel = QtWidgets.QLabel(materialsFrame)
        self.browseLabel.setObjectName("browseLabel")
        self.commandsBar.addWidget(self.browseLabel)
        self.filterLineEdit = QtWidgets.QLineEdit(materialsFrame)
        self.filterLineEdit.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border: 2px solid #90b124; ")
        self.filterLineEdit.setObjectName("filterLineEdit")
        self.commandsBar.addWidget(self.filterLineEdit)
        self.choosePlatformComboBox = QtWidgets.QComboBox(materialsFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.choosePlatformComboBox.sizePolicy().hasHeightForWidth())
        self.choosePlatformComboBox.setSizePolicy(sizePolicy)
        self.choosePlatformComboBox.setStyleSheet("background-color: rgb(255,255,255);\n"
"border: 2px solid #90b124; ")
        self.choosePlatformComboBox.setObjectName("choosePlatformComboBox")
        self.choosePlatformComboBox.addItem("")
        self.choosePlatformComboBox.addItem("")
        self.commandsBar.addWidget(self.choosePlatformComboBox)
        self.getButton = QtWidgets.QPushButton(materialsFrame)
        self.getButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.getButton.setStyleSheet("background-color: rgb(154, 217, 59);")
        self.getButton.setObjectName("getButton")
        self.commandsBar.addWidget(self.getButton)
        self.searchMaterialsBox.addLayout(self.commandsBar, 1, 0, 1, 1)
        self.coursesList = QtWidgets.QHBoxLayout()
        self.coursesList.setObjectName("coursesList")
        self.coursesView = QtWidgets.QListView(materialsFrame)
        self.coursesView.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.coursesView.setObjectName("coursesView")
        self.coursesList.addWidget(self.coursesView)
        self.searchMaterialsBox.addLayout(self.coursesList, 2, 0, 1, 1)
        self.verticalLayout.addLayout(self.searchMaterialsBox)

        self.retranslateUi(materialsFrame)
        QtCore.QMetaObject.connectSlotsByName(materialsFrame)

    def retranslateUi(self, materialsFrame):
        _translate = QtCore.QCoreApplication.translate
        materialsFrame.setWindowTitle(_translate("materialsFrame", "Frame"))
        self.materialsLabel.setText(_translate("materialsFrame", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#90b124;\">Materials</span></p></body></html>"))
        self.refreshButton.setText(_translate("materialsFrame", "Refresh"))
        self.browseLabel.setText(_translate("materialsFrame", "Browse:"))
        self.choosePlatformComboBox.setItemText(0, _translate("materialsFrame", "Moodle"))
        self.choosePlatformComboBox.setItemText(1, _translate("materialsFrame", "Microsoft Teams"))
        self.getButton.setText(_translate("materialsFrame", "GET"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    materialsFrame = QtWidgets.QFrame()
    ui = Ui_materialsFrame()
    ui.setupUi(materialsFrame)
    materialsFrame.show()
    sys.exit(app.exec_())
