# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'robotSingInDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SignInDialog(object):
    def setupUi(self, SignInDialog):
        SignInDialog.setObjectName("SignInDialog")
        SignInDialog.setWindowModality(QtCore.Qt.NonModal)
        SignInDialog.resize(400, 300)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/bot-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SignInDialog.setWindowIcon(icon)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(SignInDialog)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.titleLabel = QtWidgets.QLabel(SignInDialog)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout_4.addWidget(self.titleLabel)
        self.credentialsLayout = QtWidgets.QVBoxLayout()
        self.credentialsLayout.setObjectName("credentialsLayout")
        self.emailLayout = QtWidgets.QVBoxLayout()
        self.emailLayout.setObjectName("emailLayout")
        self.emailLabel = QtWidgets.QLabel(SignInDialog)
        self.emailLabel.setObjectName("emailLabel")
        self.emailLayout.addWidget(self.emailLabel)
        self.emailEdit = QtWidgets.QLineEdit(SignInDialog)
        self.emailEdit.setInputMethodHints(QtCore.Qt.ImhEmailCharactersOnly)
        self.emailEdit.setObjectName("emailEdit")
        self.emailLayout.addWidget(self.emailEdit)
        self.credentialsLayout.addLayout(self.emailLayout)
        self.passwordLayout = QtWidgets.QVBoxLayout()
        self.passwordLayout.setObjectName("passwordLayout")
        self.passwordLabel = QtWidgets.QLabel(SignInDialog)
        self.passwordLabel.setObjectName("passwordLabel")
        self.passwordLayout.addWidget(self.passwordLabel)
        self.passwordEdit = QtWidgets.QLineEdit(SignInDialog)
        self.passwordEdit.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhSensitiveData)
        self.passwordEdit.setObjectName("passwordEdit")
        self.passwordLayout.addWidget(self.passwordEdit)
        self.credentialsLayout.addLayout(self.passwordLayout)
        self.verticalLayout_4.addLayout(self.credentialsLayout)
        self.buttonsLayout = QtWidgets.QHBoxLayout()
        self.buttonsLayout.setObjectName("buttonsLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonsLayout.addItem(spacerItem)
        self.signinButton = QtWidgets.QPushButton(SignInDialog)
        self.signinButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.signinButton.setObjectName("signinButton")
        self.buttonsLayout.addWidget(self.signinButton)
        self.cancelButton = QtWidgets.QPushButton(SignInDialog)
        self.cancelButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancelButton.setObjectName("cancelButton")
        self.buttonsLayout.addWidget(self.cancelButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonsLayout.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.buttonsLayout)
        self.forgotPasswordLabel = QtWidgets.QLabel(SignInDialog)
        self.forgotPasswordLabel.setObjectName("forgotPasswordLabel")
        self.verticalLayout_4.addWidget(self.forgotPasswordLabel)

        self.retranslateUi(SignInDialog)
        QtCore.QMetaObject.connectSlotsByName(SignInDialog)

    def retranslateUi(self, SignInDialog):
        _translate = QtCore.QCoreApplication.translate
        SignInDialog.setWindowTitle(_translate("SignInDialog", "SignIn!"))
        self.titleLabel.setText(_translate("SignInDialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600; color:#2daa0a;\">SIGN IN</span></p></body></html>"))
        self.emailLabel.setText(_translate("SignInDialog", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600; color:#ff3007;\">Email</span></p></body></html>"))
        self.passwordLabel.setText(_translate("SignInDialog", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600; color:#ff3007;\">Password:</span></p></body></html>"))
        self.signinButton.setText(_translate("SignInDialog", "Sign in"))
        self.cancelButton.setText(_translate("SignInDialog", "Cancel"))
        self.forgotPasswordLabel.setText(_translate("SignInDialog", "<html><head/><body><p align=\"center\"><a href=\"https://my-json-server.typicode.com/Simmiyo/fake-grades-server-rest-api\"><span style=\" font-style:italic; text-decoration: underline; color:#0000ff;\">I forgot my password</span></a></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SignInDialog = QtWidgets.QDialog()
    ui = Ui_SignInDialog()
    ui.setupUi(SignInDialog)
    SignInDialog.show()
    sys.exit(app.exec_())
